language: node_js
node_js:
  - "11.10.1"
env:
  global:
    - CC_TEST_REPORTER_ID=317702f6d837fcb427579faa3bd878a1480ad0deda7519e3e2fadbf304dd252b
  matrix:
    - REACT=16.7

install:
  - npm install

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script: npm test

after_success:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
